// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkb_7uVraFHu0uG6kjtSLaxOS5gAFC-SU',
    appId: '1:847986332012:web:ebf01a257332ba3dc42349',
    messagingSenderId: '847986332012',
    projectId: 'fitness-c99a7',
    authDomain: 'fitness-c99a7.firebaseapp.com',
    storageBucket: 'fitness-c99a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCkNKzOEkY4vuMAgu67O5Srzv7gUEladc',
    appId: '1:847986332012:android:aec72cf4bb70c81ac42349',
    messagingSenderId: '847986332012',
    projectId: 'fitness-c99a7',
    storageBucket: 'fitness-c99a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhsLaEkVlOFCJvcKy_DE6dx3o9nGkxFV4',
    appId: '1:847986332012:ios:e4d52a79bdee479bc42349',
    messagingSenderId: '847986332012',
    projectId: 'fitness-c99a7',
    storageBucket: 'fitness-c99a7.appspot.com',
    iosClientId: '847986332012-7pbq7039cg51maedbgm9757k9pj373le.apps.googleusercontent.com',
    iosBundleId: 'com.example.training',
  );
}
